### ISSUE TITLE
Possible emoji font missing

### ISSUE THREAD

**Issue by popey** [timsueberkrueb/veloren-snap#4]
Installed and launched veloren. The news has squares in the text, suggesting a font is missing.
![Screenshot_20210730_011900](https://user-images.githubusercontent.com/1841272/127581447-8d165cf0-ec1e-4f8b-a29d-4b5e80a93318.png)

**Comment by timsueberkrueb** [comment]
Good catch, thanks for reporting!

**Comment by timsueberkrueb** [comment]
It turns out that this is an upstream problem. It looks like the font (Open Sans) get bundled into the binary and the GUI library iced is [not capable of displaying color emojis](https://github.com/hecrj/iced/issues/734), yet. However, in the linked issue it is stated that non-color emojis can be rendered. Though, I assume this would also require changes in upstream Airshipper/Veloren to bundle/use such a font.

If you like you could [file an issue against upstream](https://gitlab.com/veloren/veloren) though I think it's probably not a priority for now.
